### ISSUE TITLE
HTML Proofer not working in 0.59.0

### ISSUE THREAD

**Issue by mahood73** [cibuilds/hugo#125]
I've been using this image for a while on Gitlab CI - and since the rebasing I have a problem running HTML Proofer.

If I force use of image 0.58.3 all is good, but with the 0.59.0 image I get this error:

$ htmlproofer public --allow-missing-href false --check_img_http --check_opengraph --enforce-https --check-html --only_4xx true --file-ignore public/admin/index.html --log-level :debug
Running ["OpenGraphCheck", "ImageCheck", "LinkCheck", "ScriptCheck", "HtmlCheck"] on ["public"] on *.html... 

htmlproofer 3.13.0 | Error:  invalid byte sequence in US-ASCII
ERROR: Job failed: exit code 1

The same version of HTMLProofer is in both images, and the same source (and thus output). HTML proofer 3.13.0 runs fine on my local machine so I think there's something odd in the environment somewhere.

I'm open to suggestions, but I can't seem to figure out what's going wrong here.

Let me know if you need more information from me!

**Comment by mahood73** [comment]
This is a similar issue I found - perhaps it's linked?
http://www.neilmillard.com/2017/01/30/wordpress-to-jekyll/

> The building of the site was the easy bit, with the exception of adding HTML Proofer, which didn’t want to run due to a UTF-8 argument with US-ASCII. It appears that the default Ruby Docker container is configured with US-ASCII, which really breaks some stuff. With AWS CodeBuild you specify a build file buildspec.yml with which you can configure certain settings, including environment variables.
> 
> environment_variables:
>   plaintext:
>     LC_ALL: C.UTF-8
>     ENV LANG: en_US.UTF-8
>     ENV LANGUAGE: en_US.UTF-8
> With these in place HTML Proofer was happy enough and spotted the <p> tags I mentioned earlier.

**Comment by felicianotech** [comment]
Hey. The `cibuilds/hugo:0.59` and `cibuilds/hugo:0.59:0` images were updated about 9 hours ago with the fix. This issue should have been fixed in #123 

Is there a way you can get GitLab to pull down an updated image?

**Comment by mahood73** [comment]
Thanks - I found this yesterday but didn't get chance to open the issue until today... Figures you'd have already caught it!

I've just re-tested and it's fine, thank you!

**Comment by felicianotech** [comment]
That's great. No worries, it's always better to open an issue than not to. Now I know GitLab CI users are using this image. Good to know! :smiley:
