### ISSUE TITLE
Bring back Rsync!

### ISSUE THREAD

**Issue by eddiewebb** [cibuilds/hugo#136]
Moved from `felicianotech @ 0.43` to `cibuilds/hugo:0.62` and getting an 
>/bin/bash: rsync: command not found

I think for a static site generation tool rsync should be considered a core utility to promote the generated site, but you might have better reasons for removing it.

**Comment by felicianotech** [comment]
The Hugo images using my personal namespace are old as well as Alpine-based. At some point, I removed `rsync` to slim down the image as well as I was planning on creating a separate deployment image.

I moved away from Alpine to CircleCI's Ubuntu image as of the later `cibuilds/hugo` releases and I never made the deployment image. I don't see any reason not to re-add rsync. I was using it myself as well. :smile:

---

With the next Hugo release, likely v0.63.0, this Hugo image will be Ubuntu based and need to use `sudo` for privileged commands such as running `apt-get install`.
