### ISSUE TITLE
Error: Could not open lock file

### ISSUE THREAD

**Issue by RickCogley** [cibuilds/hugo#143]
Hi Lately over the past few days, my build has been failing apparently around line 12 here: 

https://github.com/RickCogley/eSolia_2018/blob/master/.circleci/config.yml#L12

I get this error: 

```
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
```

Is there anything that can be done for this? Appreciate it if you can point me in the right direction, thank you. 

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/512328/73228600-6c01c800-41ba-11ea-941a-3a90f3b45ca0.png">

**Comment by felicianotech** [comment]
Hi.

This is due to a change with newer versions of this image were `sudo` is required for commands needing root access.

You can change your line 12 from:

```yaml
- run: apt-get update && apt-get install -y git && apt-get install -y jq
```
 to

```yaml
- run: sudo apt-get update && sudo apt-get install -y git && sudo apt-get install -y jq
```

Actually, in the new images, `git` and `jq` are already installed so you can remove this line completely if you want.

**Comment by RickCogley** [comment]
> Actually, in the new images, `git` and `jq` are already installed so you can remove this line completely if you want.

Thank you. Noted on needing `sudo` if I need `apt-get`. I went ahead and commented the lines in question out. A second repo where this was happening was also using `rsync` which appears to work without installing, as well. :)
